### ISSUE TITLE
Add a refactor cop community score

### ISSUE THREAD

**Issue by JanStevens** [refactorcop/refactorcop#12]
Hello,

I had this idea recently when I discovered that I used some gems who have a horrible code quality / bad specs and overal bad maintenance. After a while you forget about these gems and suddenly a Rails 4.2 triggers a lot of weird errors. The issue: a barely updated maintained gem.

So my idea was to add a overal `RefactorCop Health Score` (name idea's pending). It would use the following stats to generate a percentage:

- Amount of contributors (more => populaire gem so likely that an error is catched by the community and fixed by the community, to many => overal 'we have no idea where this is going lets all commit something')
- The commit flow (stead stream of commits always better)
- ofcourse the refactorcop offences
- the open issues (for a small gem 14 open issues is a lot for something like rails this is peanuts so the overal use count/project size should be included)
- The amount of forks/stars
- release dates and versioning
- everything else

**Comment by nysthee** [comment]
I my opinion this is somewhat outside the scope of what this project is willing to achieve. It could be an idea for a different app combining al those metrics in a nice overview or score system.
