### ISSUE TITLE
Rubocop todo

### ISSUE THREAD

**Issue by nysthee** [refactorcop/refactorcop#17]
I think it would be great to have a label next to the projects title to show if the project has a .rubocop_todo.yml, witch implies that the project all-ready is re-factoring code style.

**Comment by mcls** [comment]
I like that idea! 

I've also been thinking about using the projects rubocop config files if they are available, but haven't gotten around to implementing it.

**Comment by nysthee** [comment]
I wil start wit a feature-branch for the "todo-badge". Maybe you should start an issue, I'm willing to look into the the implementation of the project's rubocop config later on.

**Comment by nysthee** [comment]
Implemented in Feature/todo badge #18.
